"""
Shield — Report Generator
Renders Jinja2 templates into Markdown, HTML, or JSON reports.
"""

import json
from typing import Dict, Any
from pathlib import Path
from dataclasses import asdict
from jinja2 import Environment, FileSystemLoader, select_autoescape


class ReportGenerator:
    """Generates penetration test reports from templates"""

    def __init__(self):
        templates_dir = Path(__file__).parent / "templates"
        templates_dir.mkdir(parents=True, exist_ok=True)

        self.env = Environment(
            loader=FileSystemLoader(str(templates_dir)),
            autoescape=select_autoescape(["html"]),
            trim_blocks=True,
            lstrip_blocks=True,
        )

    def render(self, format: str, data: Dict[str, Any]) -> str:
        """Render a report in the specified format"""
        # Convert dataclass objects to dicts for Jinja2
        serializable = self._make_serializable(data)

        if format == "json":
            return json.dumps(serializable, indent=2, default=str)

        template_map = {
            "markdown": "report.md.j2",
            "html": "report.html.j2",
        }

        template_name = template_map.get(format, "report.md.j2")

        try:
            template = self.env.get_template(template_name)
            return template.render(**serializable)
        except Exception as e:
            # Fallback to basic rendering
            return self._fallback_render(serializable, format)

    def _make_serializable(self, data: Dict[str, Any]) -> Dict[str, Any]:
        """Convert dataclass objects to plain dicts"""
        result = {}
        for key, value in data.items():
            if isinstance(value, list):
                result[key] = [
                    asdict(item) if hasattr(item, "__dataclass_fields__") else item
                    for item in value
                ]
            elif hasattr(value, "__dataclass_fields__"):
                result[key] = asdict(value)
            else:
                result[key] = value
        return result

    def _fallback_render(self, data: Dict, format: str) -> str:
        """Fallback rendering when templates aren't available"""
        findings = data.get("findings", [])
        summary = data.get("findings_summary", {})

        lines = [
            f"# 🔐 Penetration Test Report",
            f"",
            f"**Target:** {data.get('target', 'N/A')}",
            f"**Date:** {data.get('date', 'N/A')}",
            f"**Session:** {data.get('session_id', 'N/A')}",
            f"**Duration:** {data.get('duration', 'N/A')}",
            f"",
            f"## Executive Summary",
            f"",
            data.get("executive_summary", "No summary available."),
            f"",
            f"## Findings Summary",
            f"",
            f"| Severity | Count |",
            f"|----------|-------|",
        ]

        for sev in ["critical", "high", "medium", "low", "info"]:
            lines.append(f"| {sev.title()} | {summary.get(sev, 0)} |")

        lines.extend(["", "## Detailed Findings", ""])

        for i, f in enumerate(findings, 1):
            sev = f.get("severity", "info").upper()
            lines.extend([
                f"### {i}. [{sev}] {f.get('title', 'Untitled')}",
                f"",
                f"**Description:** {f.get('description', 'N/A')}",
                f"",
                f"**Tool:** {f.get('tool', 'N/A')}",
                f"",
                f"**Evidence:**",
                f"```",
                f"{f.get('evidence', 'N/A')}",
                f"```",
                f"",
                f"**Remediation:** {f.get('remediation', 'N/A')}",
                f"",
                "---",
                "",
            ])

        if data.get("remediation_plan"):
            lines.extend([
                "## Remediation Plan",
                "",
                data["remediation_plan"],
                "",
            ])

        lines.append("---")
        lines.append("*Report generated by Shield CLI*")

        return "\n".join(lines)
